# -*- coding: utf-8 -*-
"""week 9(4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaqXF7H2ZQ16sfbjY4aw459Xz07X_Z2S

Q=1 Load the "titanic" dataset using the load_dataset function of seaborn . Use plotly expressto plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns

titanic=sns.load_dataset("titanic")

titanic

titanic.head()

titanic.tail()

import plotly.graph_objects as go

fig=go.Figure(data=[go.Scatter(x=titanic.age)	])
fig.show()

fig=go.Figure(data=[go.Scatter(x=titanic.fare	)	])
fig.show()



"""Q-2 Using the tips dataset in the plotly library ,plot a box plot using plotly express."""

tips=sns.load_dataset('tips')

tips

fig=go.Figure(data=[go.Box(x=tips.total_bill)])
fig.show()

fig=go.Figure(data=[go.Box(x=tips.tip	)])
fig.show()

fig=go.Figure(data=[go.Box(x=tips.sex)])
fig.show()



"""Q-3 Using the tips dataset in the plotly library ,plot a histogram for x='sex' and y='total_bill' columns in tips dataset. Also use the 'smoker' columns with the pattern_shape parameters and the 'day'
columns with the colur parameter.
"""

fig=go.Figure(data=[go.Histogram(x=tips.sex, y=tips.total_bill)])
fig.show()

fig=go.Figure(data=[go.Histogram(x=tips.smoker, y=tips.day)])
fig.show()



"""Q-4 Using the iris dataset in the plotly library ,plot a scatter matrix plot , using the 'species' columnsfor the color parameter."""

iris=sns.load_dataset("iris")

iris

fig=go.Figure(data=[go.Scatter(x=iris.species)])
fig.show()

fig=go.Figure(data=[go.Scatter(x=iris.sepal_length	,y=iris.petal_length)])
fig.show()



"""Q-5 What is distplot ? Using plotly express , plot a distplot.

Ans-5 The distplot figure factory display a combination of statistical representation of numerical data ,such as histogram ,kernel density estimation or normal curve , and rug plot.
"""

import numpy as np

import plotly.figure_factory as ff

hist_data=[np.random.rand(100)]
labels=['distplot']
figure=ff.create_distplot(hist_data,labels)
figure.show()

